MaxXY: 5000
MinXY: -5000
Retries: 4
Cooldown: 30
Cost: 0
Wait: 5
DoCommands: false
dropPlayerFromAbove: false
BlockedBiomes:
  - 'DEEP_OCEAN'
  - 'OCEAN'
  - 'FROZEN_OCEAN'
PostCommands:
  - 'title %PLAYER% times 20 100 20'
  - 'title %PLAYER% title ["",{"text":"Wilderness","color":"green","bold":false}]'
  - 'title %PLAYER% subtitle ["",{"text":"Its too dangerous to go alone.","color":"yellow"}]'