# Wilderness-Tp configuration file
# .
# You can retrieve all those parameters with explanation on the online default config:
# https://github.com/AcmeProject/WildernessTp/blob/master/src/main/resources/config.yml
# .
# Detailled & up2date plugin permissions list can be read here:
# https://github.com/AcmeProject/WildernessTp/blob/master/src/main/resources/plugin.yml
# .
# bonus memo:
# - Sounds: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html 
# - Biomes: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html
# - Blocks: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# - Bar colors: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
# - Bar styles: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html
# - Gamemodes: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/GameMode.html
# - Effects: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html
# FYI, you really should consider using Paper (https://papermc.io)
# or any fork of it (e.g. Tuinity, Purpur, etc.) so that you benefit from async chunk generation/loading

# use "debug: true" to provide debug messages in console/logs to assist in fixing bugs
debug: false

# If true, cooldown messages will use actionbar instead of chat
# (this is useful not to spam it when players tries to reach a portal)
cooldownMsgUsesActionBar: true

# dere, configurable
enableGUI: true

# If true, a bossbar will be displayed to the player while waiting for the RTP proceed
enableBar: true
barColor:
  searching: YELLOW
  waiting: GREEN
barStyle:
  searching: SEGMENTED_6
  waiting: SOLID

# If false, cooldowns are per world not global
shareCoolDown: true # /!\ If true, overriden values of "Cooldown" will be ignored
# If true, extinguish adjacent blocks in nether after a WildTP
callFiremenInNether: false # (Ignored if not in nether)

# If true, if you request a RTP, you cannot move until its done
freezeWhileRTP: false
# If true, if you request a RTP and move, this will cancel it
moveCancelRTP: true

# Sound played when your player gone wild /!\ Invalid values will disable it
Sound: ENTITY_ENDERMAN_TELEPORT

BlockedBiomes: # Use « [] » if you don't want to restrict
- COLD_OCEAN
- DEEP_COLD_OCEAN
- DEEP_FROZEN_OCEAN
- DEEP_LUKEWARM_OCEAN
- DEEP_OCEAN
- DEEP_WARM_OCEAN
- FROZEN_OCEAN
- FROZEN_OCEAN
- LUKEWARM_OCEAN
- OCEAN
- RIVER
- WARM_OCEAN

BlockedBlocks: # Use « [] » if you don't want to restrict
- CACTUS
- FIRE
- LAVA
- MAGMA_BLOCK
- AIR
- VOID_AIR
- CAVE_AIR

Portals:
  # Gamemode NOT listed here will ignore portals (e.g., remove CREATIVE if you don't want to be teleported when in a portal while in creative mode)
  Gamemodes:
  - ADVENTURE
  - SURVIVAL
  - CREATIVE
  # If true, a player enterring a portal is frozen until it's done
  freezeWhileRTP: false
  # If true, if you enter a portal and move, this will cancel the RTP
  moveCancelRTP: true
  # Max size in each axis (in block, 0 will disable the limitation)
  # /!\ This doesn't affect previously created portals.
  xMax: 10
  yMax: 10
  zMax: 10
  # When a player try to reach a portal when being in cooldown, this push him back
  push: 1.0 # Force of the push (float), put 0 or less to disable
  # /!\ Big values can be fun but will hurt & irritate your players... I mean literally!

Bypass: # /!\ Those settings FORCE bypass, whether the player has permission or not!
  # Force permission « wild.wildtp.cooldown.bypass »
  cooldown:
    COMMAND: false # When the player tp via command
    GUI: false     # When using the GUI
    OTHERGUY: true # When another player teleport you (typically staff)
    PORTAL: false  # When passing a wild portal
    SIGN: false    # When interacting with a wild sign
  # Force permission « wild.wildtp.world.*.free »
  cost:
    COMMAND: false
    GUI: false
    OTHERGUY: true
    PORTAL: false
    SIGN: false
  # Force permission « wild.wildtp.delay.bypass »
  delay:
    COMMAND: false
    GUI: false
    OTHERGUY: true
    PORTAL: true
    SIGN: false

# Format is <PotionEffectType> or <PotionEffectType>:<multiplier> (integer)
# /!\ Invalid multiplier will fallback to 0
Effects:
  COMMAND:
  - BLINDNESS
  - CONFUSION:99
  - SLOW_DIGGING:3
  GUI: [] # <== This represent an empty list (no effects)
  JOIN: # Require « teleportNewPlayers: true »
  - BLINDNESS
  - CONFUSION
  OTHERGUY: []
  PORTAL:
  - BLINDNESS
  - CONFUSION
  - INVISIBILITY
  - SLOW:2
  SIGN: []

# Bounds of the wildness (named XY and not XZ... Another proof! #CatEarthSociety)
MinXY: -5000
MaxXY: 5000
# If true, border is recalculated each RTP - useful if you set your border to grow/shrink (so you should keep it false if not required)
movingBorder: false

Wait: 0      # (seconds) Time the player have to wait between he type the command and tp be sent in wild
Retries: 6   # Max attempts the plugin will try to find a safe place to tp the player
Cooldown: 0 # (seconds) Time to wait before player can re-do again

Cost: 0 # Money cost of a RTP (requires Vault)
paidTPconfirmation: 30 # If the RTP has a cost, a confirmation will be asked to the player...
# This is (in second) the time this pending RTP stay valid. (set to 0 if you don't want confirmations) 

teleportNewPlayers: false  # Choose "true" if you are not proud of your spawn
dropPlayerFromAbove: false # Choose "true" if you vocal on dumcord and want to hear them scream. Or as I originally intended this to be, a dropship-like teleport
dropPlayerFromHeight: 255  # Height from where the player is dropped (if dropPlayerFromAbove is true)
# /!\ Using too high values can cause issues in some cases... Test before letting your players use them.
# For example, using 300 with datapack "EndAboveOverworld" load the end, then reload overworld...
# (This stops the sound prematurely, perturb the player + load / unload chunks for nothing)

DoCommands: false # « Do it! » (Shia Labeouf)
PostCommands: # Ignored if DoCommands is false
  - 'title %PLAYER% times 20 100 20'
  - 'title %PLAYER% title ["",{"text":"Wilderness","color":"green","bold":false}]'
  - 'title %PLAYER% subtitle ["",{"text":"Its too dangerous to go alone.","color":"yellow"}]'
# Note: %PLAYER% will be replaced by... the player name! (if you had it, you won 1 point)
# You can also use %X% and %Z% as X and Z coords of new location of the player.
# Example:
# - 'title %PLAYER% subtitle ["",{"text":"Coords %X% / %Z% are so wild!","color":"yellow"}]'

useRandomWorlds: false
randomWorlds: # Ignored if useRandomWorlds is false
  world: 1337
  world_nether: 42

useGlobalClaimCheck: true # (if GriefPrevention plugin is found, default value will be false)
useAlternativeGlobalClaimCheck: false # If you see errors like "Could not pass BlockBreakEvent..." then enable this instead of the global claim check

signTexts:
  # This is what player have to type on a sign (first or second line) to create a WildTP sign
  createWith: "[wildtp]" # (case insensitive: means you can write with caps or not)
  # (optionaly, the player can write the EXACT name or alias of a world ON LINE 2)

  # This is how WildTP signs will appear
  # /!\ If you change this, previously created signs will no more work until you recreate them!
  #     (same if you use %COST% in texts and change the amount)
  line1: "&4===================="
  line2: "[&1Wild&0]"
  line3: "&4===================="
  # (line4 is reserved to display the (optional) world name)
  # You can use %COST% as a placeholder for the amount of money the server will rob to the player

  costFree: "&b&lFREE"    # How to display cost when it's free
  costMoney: "&4%COST% $" # How to display cost when it takes money

  # Example:
  # line1: "&8== %COST% &8=="    # will give « &8== &b&lFREE &8== » OR « &8== &4100 $ &8== »
  # line2: "[&1Wild&0]"
  # line3: "&8(right click)"

# As world names will appear on your WildTP signs, and signs cannot have long lines,
# if a name is too long, it will creates issues (not recognized by the plugin...)
# so you should create short aliases for your worlds (which could also be more understandable by you players)
worldsAliaz: {}
# /!\ This parameter is automatically filled (if empty) by your existing worlds when the plugin starts.
# so, you will see something like that:
#
# worldsAliaz:
#   world: world
#   world_nether: world_nether
#   world_the_end: world_the_end
#
# Now, if you want to customize how worlds name will appear on WildTP signs, do this:
# (this example, you can put whatever names you want...)
#
# worldsAliaz:
#   world: ElMondo
#   world_nether: Hell
#   world_the_end: End

# You can override almost all parameters per world in this section.
# This is pretty simple: You just have to add a section with the name of the world (not the alias, its real name),
# and put in it the parameter you want to override. All omitted ones will use default config.
overrides: {} # <=== « {} » means there is no overrides at all

# Examples:
#
# overrides: # (with all parameters you can override)
#   an_example:
#     BlockedBiomes:
#       - JUNGLE
#       - MOUNTAINS
#     BlockedBlocks:
#       - STONE
#       - GRASS
#     freezeWhileRTP: true
#     moveCancelRTP: false
#     MinXY: -1000
#     MaxXY: 1000
#     movingBorder: true
#     Wait: 0
#     Retries: 1
#     Cooldown: 0
#     Cost: 99999
#     paidTPconfirmation: 120
#     DoCommands: false
#     PostCommands: []
#     callFiremenInNether: false
#     dropPlayerFromAbove: true
#     dropPlayerFromHeight: 128
#     Bypass:
#       cooldown:
#         PORTAL: true
#       cost:
#         PORTAL: true
#       delay:
#         PORTAL: true
#     enableBar: true
#     barColor: 
#       searching: PINK
#       waiting: PURPLE
#     barStyle:
#       searching: SEGMENTED_20
#       waiting: SEGMENTED_12
#     Portals:
#       Gamemodes:
#         - ADVENTURE
#         - CREATIVE
#         - SPECTATOR
#         - SURVIVALL
#       freezeWhileRTP: true
#       moveCancelRTP: false
#       xMax: 2
#       yMax: 3
#       zMax: 2
#       push: 0
#     Effects:
#       COMMAND:
#         - BLINDNESS
#       GUI: []
#       JOIN: []
#       OTHERGUY: []
#       PORTAL:
#         - CONFUSION
#       SIGN: []
#
#   another_working_example: # (to show you don't have to add all parameters)
#     MinXY: -50000
#     MaxXY: 50000
