name: Wild
version: '2.0'
authors: [LaxWasHere,RoboMWM]
main: net.poweredbyhate.wildtp.WildTP
softdepend: [GriefPrevention,Vault]
commands:
  wild:
    aliases: [wilderness,rtp]
  wildtp:
    aliases: [wtp]
