name: Wild
version: '2.7'
authors: [LaxWasHere,RoboMWM]
main: net.poweredbyhate.wildtp.WildTP
softdepend: [GriefPrevention,Vault,WorldBorder]
api-version: 1.13
commands:
  wild:
    aliases: [wilderness,rtp]
  wildtp:
    aliases: [wtp]
permissions:
  wild.wildtp.sign:
    default: true