name: Wild
version: 1.28
author: [LaxWasHere,RoboMWM]
main: net.poweredbyhate.wildtp.WildTP
softdepend: [GriefPrevention,Vault,Factions,MassiveCore]
commands:
  wild:
    aliases: [wilderness,rtp]
  wildtp:
    aliases: [wtp]
