name: Wild
version: 1.25
author: RoboMWM
main: net.poweredbyhate.wildtp.WildTP
softdepend: [GriefPrevention,Vault]
commands:
  wild:
    aliases: [wilderness,rtp]
  wildtp:
    aliases: [wtp]
