name: Wild
version: 1.34
author: [LaxWasHere,RoboMWM]
main: net.poweredbyhate.wildtp.WildTP
softdepend: [GriefPrevention,Vault]
commands:
  wild:
    aliases: [wilderness,rtp]
  wildtp:
    aliases: [wtp]
