name: Wild
version: 1.8
author: [LaxWasHere,RoboMWM]
main: net.poweredbyhate.wildtp.WildTP
softdepend: GriefPrevention
commands:
  wild:
    aliases: [wilderness,rtp]
  wildtp:
    aliases: [wtp]
